<?php
function hljs_get_style_list() {
  return array(
    'Default' => 'default',
    'Dark' => 'dark',
    'FAR' => 'far',
    'IDEA' => 'idea',
    'Sunburst' => 'sunburst',
    'Zenburn' => 'zenburn',
    'Visual Studio' => 'vs',
    'Ascetic' => 'ascetic',
    'Magula' => 'magula',
    'GitHub' => 'github',
    'Google Code' => 'googlecode',
    'Brown Paper' => 'brown_paper',
    'School Book' => 'school_book',
    'IR Black' => 'ir_black',
    'Solarized - Dark' => 'solarized_dark',
    'Solarized - Light' => 'solarized_light',
    'Arta' => 'arta',
    'Monokai' => 'monokai',
    'Monokai Sublime' => 'monokai_sublime',
    'XCode' => 'xcode',
    'Pojoaque' => 'pojoaque',
    'Rainbow' => 'rainbow',
    'Tomorrow' => 'tomorrow',
    'Tomorrow Night' => 'tomorrow-night',
    'Tomorrow Night Bright' => 'tomorrow-night-bright',
    'Tomorrow Night Blue' => 'tomorrow-night-blue',
    'Tomorrow Night Eighties' => 'tomorrow-night-eighties',
    'Railscasts' => 'railscasts',
    'Obsidian' => 'obsidian',
    'Docco' => 'docco',
    'Mono Blue' => 'mono-blue',
    'Foundation' => 'foundation',
    'Atelier Dun - Dark' => 'atelier-dune.dark',
    'Atelier Dun - Light' => 'atelier-dune.light',
    'Atelier Forest - Dark' => 'atelier-forest.dark',
    'Atelier Forest - Light' => 'atelier-forest.light',
    'Atelier Heath - Dark' => 'atelier-heath.dark',
    'Atelier Heath - Light' => 'atelier-heath.light',
    'Atelier Lakeside - Dark' => 'atelier-lakeside.dark',
    'Atelier Lakeside - Light' => 'atelier-lakeside.light',
    'Atelier Seaside - Dark' => 'atelier-seaside.dark',
    'Atelier Seaside - Light' => 'atelier-seaside.light',
    'Paraíso - Dark' => 'paraiso.dark',
    'Paraíso - Light'=> 'paraiso.light'
  );
}
?>